### ISSUE TITLE
Calls obsolete Jackson method

### ISSUE THREAD

**Issue by sjatlyft** [maxmind/GeoIP2-java#111]
https://github.com/maxmind/GeoIP2-java/blob/50cf6b99205eac577f82c940e11dffb68ca7bd46/src/main/java/com/maxmind/geoip2/DatabaseReader.java#L159

I tested, geoip2 2.12.0 and 2.6.0, both throw this error. Looks like 2.5.0 is usable.
 ```
Stacktrace:
Caused by: java.lang.NoSuchMethodError: com.fasterxml.jackson.databind.node.ArrayNode.<init>(Lcom/fasterxml/jackson/databind/node/JsonNodeFactory;Ljava/util/List;)V
  at com.maxmind.db.Decoder.decodeArray(Decoder.java:272)
  at com.maxmind.db.Decoder.decodeByType(Decoder.java:156)
  at com.maxmind.db.Decoder.decode(Decoder.java:147)
  at com.maxmind.db.Decoder.decodeMap(Decoder.java:281)
  at com.maxmind.db.Decoder.decodeByType(Decoder.java:154)
  at com.maxmind.db.Decoder.decode(Decoder.java:147)
  at com.maxmind.db.Decoder.decode(Decoder.java:87)
  at com.maxmind.db.Reader.<init>(Reader.java:132)
  at com.maxmind.db.Reader.<init>(Reader.java:116)
  at com.maxmind.geoip2.DatabaseReader.<init>(DatabaseReader.java:39)
  at com.maxmind.geoip2.DatabaseReader.<init>(DatabaseReader.java:27)
  at com.maxmind.geoip2.DatabaseReader$Builder.build(DatabaseReader.java:133)
  at $anonfun$1.apply(<console>:72)
  at $anonfun$1.apply(<console>:56)
  at org.apache.spark.sql.catalyst.expressions.GeneratedClass$SpecificUnsafeProjection.subExpr$(Unknown Source)
  at org.apache.spark.sql.catalyst.expressions.GeneratedClass$SpecificUnsafeProjection.apply(Unknown Source)
  at org.apache.spark.sql.catalyst.expressions.GeneratedClass$SpecificUnsafeProjection.apply(Unknown Source)
  at scala.collection.Iterator$$anon$11.next(Iterator.scala:409)
  at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage1.agg_doAggregateWithKeys$(Unknown Source)
  at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage1.processNext(Unknown Source)
  at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
  at org.apache.spark.sql.execution.WholeStageCodegenExec$$anonfun$10$$anon$1.hasNext(WholeStageCodegenExec.scala:614)
  at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:408)
  at org.apache.spark.shuffle.sort.BypassMergeSortShuffleWriter.write(BypassMergeSortShuffleWriter.java:125)
  at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:96)
  at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:53)
  at org.apache.spark.scheduler.Task.run(Task.scala:109)
  at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:345)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
  at java.lang.Thread.run(Thread.java:748)
```

More info:
https://stackoverflow.com/questions/34958520/nosuchmethodexception-in-maxmind-geoip-dependency-jackson-databind-built-with-mv

**Comment by oschwald** [comment]
That constructor was [added in 2.7](https://fasterxml.github.io/jackson-databind/javadoc/2.7/com/fasterxml/jackson/databind/node/ArrayNode.html#ArrayNode\(com.fasterxml.jackson.databind.node.JsonNodeFactory,%20java.util.List\)). We depend on 2.9.5, which includes it. Upgrading your Jackson version should fix the issue.

**Comment by SWaiter** [comment]
yes， if I can only use the old version, is there a solution?

**Comment by SWaiter** [comment]
Because the Jackson version in my hive cluster is relatively low and there is a high risk of change，so I only use old version.
