### ISSUE TITLE
java.lang.OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by avifatal** [maxmind/GeoIP2-java#123]
Hi,
Im using the the version `compile('com.maxmind.geoip2:geoip2:2.12.0')` .  
After 50-100 calls to maxmind I am getting the the exception you can see bellow.

I have a simple usage: 
```

  @Override
    public String getCountry(String ip) {
        String result = "";
        Resources resources = AppBeans.get(Resources.class);
        InputStream inputStream = resources.getResourceAsStream("classpath:com/platform/crm/GeoLite2-City.mmdb"); // this returns null
        DatabaseReader reader = null;
        try {
            reader = new DatabaseReader.Builder(inputStream).build();

        InetAddress ipAddress = InetAddress.getByName(ip);
        CityResponse response = reader.city(ipAddress);
        result =  response.getCountry().getIsoCode();
        } catch (Exception e) {
            log.error("cant find country for ip " + ip);
        }
        return result;
    }
```

I saw this qustion here, but did not see a solution yet...
Thanks

```
java.lang.OutOfMemoryError: Java heap space
        at java.util.Arrays.copyOf(Arrays.java:3236) ~[na:1.8.0_181]
        at java.io.ByteArrayOutputStream.grow(ByteArrayOutputStream.java:118) ~[na:1.8.0_181]
        at java.io.ByteArrayOutputStream.ensureCapacity(ByteArrayOutputStream.java:93) ~[na:1.8.0_181]
        at java.io.ByteArrayOutputStream.write(ByteArrayOutputStream.java:153) ~[na:1.8.0_181]
        at com.maxmind.db.BufferHolder.<init>(BufferHolder.java:64) ~[maxmind-db-1.2.2.jar:na]
        at com.maxmind.db.Reader.<init>(Reader.java:89) ~[maxmind-db-1.2.2.jar:na]
        at com.maxmind.geoip2.DatabaseReader.<init>(DatabaseReader.java:64) ~[geoip2-2.12.0.jar:2.12.0]
        at com.maxmind.geoip2.DatabaseReader.<init>(DatabaseReader.java:54) ~[geoip2-2.12.0.jar:2.12.0]
        at com.maxmind.geoip2.DatabaseReader$Builder.build(DatabaseReader.java:160) ~[geoip2-2.12.0.jar:2.12.0]
        at com.platform.crm.service.CountryByIpServiceBean.getCountry(CountryByIpServiceBean.java:36) ~[app-core-0.1-SNAPSHOT.jar:na]
```

**Comment by oschwald** [comment]
You shouldn't be opening the database on every call. The garbage collector can not reclaim all the memory you are using to read the whole database into memory repeatedly, causing you to run out of memory.

**Comment by avifatal** [comment]
So if my service is singleton I can make the `DatabaseReader reader` a private class memeber and set it from the constructor?
Thanks

**Comment by oschwald** [comment]
That should work.
