### ISSUE TITLE
NoSuchMethodError: org.apache.commons.codec.binary.Base64.<init>(I)V

### ISSUE THREAD

**Issue by TanzimChowdhury** [maxmind/GeoIP2-java#128]
Try to run the City Service example code but this error comes up in the console
Exception in thread "main" java.lang.NoSuchMethodError: org.apache.commons.codec.binary.Base64.<init>(I)V
	at org.apache.http.impl.auth.BasicScheme.authenticate(BasicScheme.java:166)
	at com.maxmind.geoip2.WebServiceClient.getResponse(WebServiceClient.java:332)
	at com.maxmind.geoip2.WebServiceClient.responseFor(WebServiceClient.java:314)
	at com.maxmind.geoip2.WebServiceClient.city(WebServiceClient.java:288)
	at NewTesterClass.main(NewTesterClass.java:22)
Using eclipse

**Comment by oschwald** [comment]
It sounds like you have an outdated version of `commons-codec`, an indirect dependency. What is the output of `mvn dependency:tree`?

**Comment by oschwald** [comment]
Closing due to lack of information. It sounds like a dependency version mismatch as stated above.
