### ISSUE TITLE
my GeoIP2-ISP.mmdb file exists under resource folder but cant access

### ISSUE THREAD

**Issue by naym9860** [maxmind/GeoIP2-java#140]
here is my code
File database = new File(
				URLDecoder.decode(getClass().getClassLoader().getResource("GeoIP2-ISP.mmdb").getFile(), "UTF-8"));
		
		DatabaseReader reader = new DatabaseReader.Builder(database).build();

		InetAddress ipAddress = InetAddress.getByName(ip);

		IspResponse response = null;
		try {
			response = reader.isp(ipAddress);

		} catch (GeoIp2Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();

but when i am running the application i am getting below issue
INFO: Illegal access: this web application instance has been stopped already. Could not load [GeoIP2-ISP.mmdb]. The following stack trace is thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal access.
java.lang.IllegalStateException: Illegal access: this web application instance has been stopped already. Could not load [GeoIP2-ISP.mmdb]. The following stack trace is thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal access.
	at org.apache.catalina.loader.WebappClassLoaderBase.checkStateForResourceLoading(WebappClassLoaderBase.java:1385)
	at org.apache.catalina.loader.WebappClassLoaderBase.getResource(WebappClassLoaderBase.java:1038)
	at service.BidRequestMethods.getIspFromMaxMind(BidRequestMethods.java:170)
	at service.BidRequestMethods.getOperator(BidRequestMethods.java:132)
	at service.BidRequestMethods.matchOperator(BidRequestMethods.java:122)
	at service.BidRequestMethods.matchTarget(BidRequestMethods.java:62)
	at servlet.BidRequestRetriever.doPost(BidRequestRetriever.java:59)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:660)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:526)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:678)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:860)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1587)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)

**Comment by oschwald** [comment]
The stack trace doesn't mention this module at all, which leads me to believe that the issue is unrelated to the database reader. That said, if you are loading the database from a JAR file, you will likely want to pass it to the reader as a stream rather than a file. The file within the JAR cannot be memory mapped. Also, you should not be decoding the database as UTF-8.
