### ISSUE TITLE
java.lang.ClassNotFoundException: com.maxmind.geoip2.DatabaseReader$Builder

### ISSUE THREAD

**Issue by Venky144** [maxmind/GeoIP2-java#176]
I'm not using Maven, As instructed  i have added all the jars from the latest release page. I'm still getting the class not found exception. 

![geoIpJars](https://user-images.githubusercontent.com/60193496/72920541-5d209e80-3cfe-11ea-9e50-2916386df4e6.jpg)

Caused by: java.lang.ClassNotFoundException: com.maxmind.geoip2.DatabaseReader$Builder
	at java.net.URLClassLoader.findClass(URLClassLoader.java:434)
	at com.ibm.ws.bootstrap.ExtClassLoader.findClass(ExtClassLoader.java:214)
	at java.lang.ClassLoader.loadClassHelper(ClassLoader.java:703)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:682)
	at com.ibm.ws.bootstrap.ExtClassLoader.loadClass(ExtClassLoader.java:120)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:665)
	at com.ibm.ws.classloader.ProtectionClassLoader.loadClass(ProtectionClassLoader.java:62)
	at com.ibm.ws.classloader.ProtectionClassLoader.loadClass(ProtectionClassLoader.java:58)
	at com.ibm.ws.classloader.CompoundClassLoader.loadClass(CompoundClassLoader.java:584)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:665)
	at com.ibm.ws.classloader.CompoundClassLoader.loadClass(CompoundClassLoader.java:584)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:665)
	... 43 more

**Comment by oschwald** [comment]
That class is in the `geoip2-2.13.0.tar`. I am not sure how you are loading the jars. From your screenshot, I assume you are using an IDE. I would suggest asking on a support forum for the IDE.
