### ISSUE TITLE
 Numeric value (4294901908) out of range of int (-2147483648 - 2147483647)

### ISSUE THREAD

**Issue by roostapour** [maxmind/GeoIP2-java#178]
Hello,

I keep getting this error while using DBIP to geolocate IPs. I get them for these two IPs (210.11.158.104 and 210.11.158.229), both in Australia. Any idea what would be the reason?

``` com.fasterxml.jackson.databind.JsonMappingException: Numeric value (4294901908) out of range of int (-2147483648 - 2147483647)
 at [Source: UNKNOWN; line: -1, column: -1] (through reference chain: com.maxmind.geoip2.model.EnterpriseResponse["traits"]->com.maxmind.geoip2.record.Traits["autonomous_system_number"])
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:394)
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:353)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.wrapAndThrow(BeanDeserializerBase.java:1714)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:530)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:417)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1287)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:326)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:159)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:530)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:528)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:417)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1287)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:326)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:159)
	at com.fasterxml.jackson.databind.ObjectReader._bind(ObjectReader.java:1682)
	at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:977)
	at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:995)
	at com.fasterxml.jackson.databind.ObjectReader.treeToValue(ObjectReader.java:1638)
	at com.maxmind.geoip2.DatabaseReader.get(DatabaseReader.java:281)
	at com.maxmind.geoip2.DatabaseReader.getOrThrowException(DatabaseReader.java:240)
	at com.maxmind.geoip2.DatabaseReader.enterprise(DatabaseReader.java:432)```

**Comment by oschwald** [comment]
Is it possible that your database is corrupt? The 2020-02-10 database appears to have 2764 for that field for both of those IPs.

**Comment by roostapour** [comment]
I do have the enterprise version. So I am running the php code to get the db file. I tested it today and there was the same error . Are you testing with the free version?

**Comment by oschwald** [comment]
What version of this library are you using?

I tested against the latest Enterprise version. Assuming you have `mmdblookup` from `libmaxminddb` installed, would you be able to provide me with the output of this command?

```
mmdblookup -v -f /usr/local/share/GeoIP/GeoIP2-Enterprise.mmdb -i 210.11.158.104
```

After updating the path to the database as appropriate.

Also, the `md5sum` of the database would be helpful.

**Comment by roostapour** [comment]
Here are the results:

```
  Database metadata
    Node count:    32763515
    Record size:   32 bits
    IP version:    IPv6
    Binary format: 2.0
    Build epoch:   1581559203 (2020-02-13 02:00:03 UTC)
    Type:          DBIP-Location-ISP (compat=Enterprise)
    Languages:     en de es fr ja pt-BR ru zh-CN fa ko
    Description:
      en:   DB-IP.com - IP to Location + ISP
      fr:   DB-IP.com - IP vers Localisation + ISP


  {
    "city":
      {
        "geoname_id":
          8348897 <uint32>
        "names":
          {
            "en":
              "Forest Lodge" <utf8_string>
          }
      }
    "continent":
      {
        "code":
          "OC" <utf8_string>
        "geoname_id":
          6255151 <uint32>
        "names":
          {
            "de":
              "Ozeanien" <utf8_string>
            "en":
              "Oceania" <utf8_string>
            "es":
              "Oceanía" <utf8_string>
            "fa":
              "اقیانوسیه" <utf8_string>
            "fr":
              "Océanie" <utf8_string>
            "ja":
              "オセアニア" <utf8_string>
            "ko":
              "오세아니아" <utf8_string>
            "pt-BR":
              "Oceania" <utf8_string>
            "ru":
              "Океания" <utf8_string>
            "zh-CN":
              "大洋洲" <utf8_string>
          }
      }
    "country":
      {
        "geoname_id":
          2077456 <uint32>
        "is_in_european_union":
          false <boolean>
        "iso_code":
          "AU" <utf8_string>
        "names":
          {
            "de":
              "Australien" <utf8_string>
            "en":
              "Australia" <utf8_string>
            "es":
              "Australia" <utf8_string>
            "fa":
              "استرالیا" <utf8_string>
            "fr":
              "Australie" <utf8_string>
            "ja":
              "オーストラリア" <utf8_string>
            "ko":
              "오스트레일리아" <utf8_string>
            "pt-BR":
              "Austrália" <utf8_string>
            "ru":
              "Австралия" <utf8_string>
            "zh-CN":
              "澳大利亚" <utf8_string>
          }
      }
    "location":
      {
        "latitude":
          -33.883300 <double>
        "longitude":
          151.183000 <double>
        "time_zone":
          "Australia/Darwin" <utf8_string>
        "weather_code":
          "ASXX8436" <utf8_string>
      }
    "postal":
      {
        "code":
          "2037" <utf8_string>
      }
    "subdivisions":
      [
        {
          "geoname_id":
            2155400 <uint32>
          "iso_code":
            "NSW" <utf8_string>
          "names":
            {
              "en":
                "New South Wales" <utf8_string>
              "fr":
                "Nouvelle-Galles du Sud" <utf8_string>
              "pt-BR":
                "Nova Gales do Sul" <utf8_string>
              "ru":
                "Новый Южный Уэльс" <utf8_string>
            }
        }
        {
          "geoname_id":
            6619279 <uint32>
          "names":
            {
              "de":
                "Sydney" <utf8_string>
              "en":
                "Sydney" <utf8_string>
              "fr":
                "Sydney" <utf8_string>
              "ja":
                "シティ・オブ・シドニー" <utf8_string>
              "pt-BR":
                "Cidade de Sydney" <utf8_string>
              "ru":
                "Сидней" <utf8_string>
              "zh-CN":
                "悉尼市" <utf8_string>
            }
        }
      ]
    "traits":
      {
        "autonomous_system_number":
          4294901908 <uint32>
        "autonomous_system_organization":
          "AS4294901908" <utf8_string>
        "connection_type":
          "Corporate" <utf8_string>
        "isp":
          "AS4294901908" <utf8_string>
        "organization":
          "AAPT Limited" <utf8_string>
      }
  }
```

For ```md5sum``` :  ```4645a7cd1c1377fdaa7baef79599b1b9```

**Comment by oschwald** [comment]
Thanks. It looks like you are using the DB-IP database. I believe the particular record in question contains some invalid data.

That said, this API should allow for any unsigned 32 bit number and so I am inclined to leave this open. Fixing this will require a breaking change and it will have to wait until the next major version release.

**Comment by roostapour** [comment]
Thanks. Any estimate on when will be a major version release?

**Comment by oschwald** [comment]
We have no plans to do a major release in the near future. I would suggest following up with DB-IP about the invalid ASN information in their database.
