### ISSUE TITLE
InvalidDatabaseException from new GeoIP2 City datebase

### ISSUE THREAD

**Issue by syoh0708** [maxmind/GeoIP2-java#196]
We are using GeoIP2 City datebase and updated new Database.
When library initialize DatabaseReader, it checks existance of METADATA_START_MARKER from database file.
But the database file does not appear to have metadata.

We used GeoIP2-City.mmdb file updated at 2020-05-19.
GeoIP2-java version : com.maxmind.geoip2:geoip2:2.13.0

```
Caused by: com.maxmind.db.InvalidDatabaseException: Could not find a MaxMind DB metadata marker in this file (<InputStream>). Is this a valid MaxMind DB file?
	at com.maxmind.db.Reader.findMetadataStart(Reader.java:282)
	at com.maxmind.db.Reader.<init>(Reader.java:129)
	at com.maxmind.db.Reader.<init>(Reader.java:89)
	at com.maxmind.geoip2.DatabaseReader.<init>(DatabaseReader.java:93)
	at com.maxmind.geoip2.DatabaseReader.<init>(DatabaseReader.java:64)
	at com.maxmind.geoip2.DatabaseReader$Builder.build(DatabaseReader.java:226)
```

Let me know if you need any more information.
Thanks in advance!

**Comment by horgh** [comment]
How are you downloading the database? Is it possible the .mmdb was not fully extracted from the compressed file?

**Comment by syoh0708** [comment]
It was my mistake.
It was because my team decided to use git lfs service to use mmdb file.

Sorry for false report.
