### ISSUE TITLE
Local unit tests succeed but generates a NoSuchMethodError running on a cluster

### ISSUE THREAD

**Issue by drinkemc** [maxmind/GeoIP2-java#213]
I am currently running Java 8, Scala 2.12.10, Spark 2.4.4 and am leveraging GeoLite2-City.mmdb via the geoip2 api version 2.13.0.  I have created a dependency override in my build.sbt file to force jackson-module-scala 2.10.1 such that the jackson.databind dependencies are respected.

Currently I am reading storing the GeoLite2-City database as an S3 object which is read into a file which is then passed to the DatabaseReader.Builder constructor.  When I build and run my unit tests locally everything works as expected, but when I submit the JAR as a spark step the application fails with the following stack trace:

20/09/01 18:37:02 INFO Client: 
	 client token: N/A
	 diagnostics: User class threw exception: java.lang.NoSuchMethodError: com.fasterxml.jackson.databind.node.ArrayNode.<init>(Lcom/fasterxml/jackson/databind/node/JsonNodeFactory;Ljava/util/List;)V
	at com.maxmind.db.Decoder.decodeArray(Decoder.java:270)
	at com.maxmind.db.Decoder.decodeByType(Decoder.java:155)
	at com.maxmind.db.Decoder.decode(Decoder.java:146)
	at com.maxmind.db.Decoder.decodeMap(Decoder.java:279)
	at com.maxmind.db.Decoder.decodeByType(Decoder.java:153)
	at com.maxmind.db.Decoder.decode(Decoder.java:146)
	at com.maxmind.db.Decoder.decode(Decoder.java:88)
	at com.maxmind.db.Reader.<init>(Reader.java:132)
	at com.maxmind.db.Reader.<init>(Reader.java:116)
	at com.maxmind.geoip2.DatabaseReader.<init>(DatabaseReader.java:95)
	at com.maxmind.geoip2.DatabaseReader.<init>(DatabaseReader.java:64)
	at com.maxmind.geoip2.DatabaseReader$Builder.build(DatabaseReader.java:226)
	at MobileDataEnrichment$.<init>(MobileDataEnrichment.scala:46)
	at MobileDataEnrichment$.<clinit>(MobileDataEnrichment.scala)
	at MobileDataEnrichment.main(MobileDataEnrichment.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.yarn.ApplicationMaster$$anon$2.run(ApplicationMaster.scala:678)

	 ApplicationMaster host: ip-10-192-37-52.aws.lijit.com
	 ApplicationMaster RPC port: 46767
	 queue: default
	 start time: 1598985337885
	 final status: FAILED
	 tracking URL: http://ip-10-192-47-208.aws.lijit.com:20888/proxy/application_1598985259122_0001/
	 user: hadoop
20/09/01 18:37:02 ERROR Client: Application diagnostics message: User class threw exception: java.lang.NoSuchMethodError: com.fasterxml.jackson.databind.node.ArrayNode.<init>(Lcom/fasterxml/jackson/databind/node/JsonNodeFactory;Ljava/util/List;)V
	at com.maxmind.db.Decoder.decodeArray(Decoder.java:270)
	at com.maxmind.db.Decoder.decodeByType(Decoder.java:155)
	at com.maxmind.db.Decoder.decode(Decoder.java:146)
	at com.maxmind.db.Decoder.decodeMap(Decoder.java:279)
	at com.maxmind.db.Decoder.decodeByType(Decoder.java:153)
	at com.maxmind.db.Decoder.decode(Decoder.java:146)
	at com.maxmind.db.Decoder.decode(Decoder.java:88)
	at com.maxmind.db.Reader.<init>(Reader.java:132)
	at com.maxmind.db.Reader.<init>(Reader.java:116)
	at com.maxmind.geoip2.DatabaseReader.<init>(DatabaseReader.java:95)
	at com.maxmind.geoip2.DatabaseReader.<init>(DatabaseReader.java:64)
	at com.maxmind.geoip2.DatabaseReader$Builder.build(DatabaseReader.java:226)
	at MobileDataEnrichment$.<init>(MobileDataEnrichment.scala:46)
	at MobileDataEnrichment$.<clinit>(MobileDataEnrichment.scala)
	at MobileDataEnrichment.main(MobileDataEnrichment.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.yarn.ApplicationMaster$$anon$2.run(ApplicationMaster.scala:678)

No matter what variation of code I use (I have tried a number of different ways) I am always met with the same error.... that there is no <init> method for the ArrayNode.  

I have also tried using the most current version of each dependency possible while still using scala 2.12 (as there is not spark support for scala 2.13 that I have seen)

**Comment by oschwald** [comment]
The error suggests that you are not using the required `jackson-databind` version when running on the cluster for some reason. `maxmind-db` requires a minimum version currently that has that constructor. There is a forthcoming version that will remove that use of `jackson-databind`, which should solve your issue, but we don't have a timeline on the release.

**Comment by drinkemc** [comment]
I have explicitly set dependency overrides the version of jackson-databind and jackson-module to correspond to the the version of maxmind-db in my build.sbt.  It has not made a difference.

**Comment by drinkemc** [comment]
after some more digging through the issues pile, seems that creating a thin JAR through shading works on newer versions also. https://github.com/maxmind/GeoIP2-java/issues/57

**Comment by oschwald** [comment]
I am glad shading worked for you. I am going to close this issue. The next major release of `maxmind-db` will no longer use `jackson-databind`, which will eliminate the need for the particular Jackson version.
