### ISSUE TITLE
in android 6.0

### ISSUE THREAD

**Issue by sa2241182** [maxmind/GeoIP2-java#288]
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.ok.mmdbtest, PID: 23806
    java.lang.NoSuchMethodError: No virtual method getParameterCount()I in class Ljava/lang/reflect/Constructor; or its super classes (declaration of 'java.lang.reflect.Constructor' appears in /system/framework/core-libart.jar)
        at com.maxmind.db.Decoder.decodeMapIntoObject(Decoder.java:397)
        at com.maxmind.db.Decoder.decodeMap(Decoder.java:342)
        at com.maxmind.db.Decoder.decodeByType(Decoder.java:162)
        at com.maxmind.db.Decoder.decode(Decoder.java:151)
        at com.maxmind.db.Decoder.decode(Decoder.java:76)
        at com.maxmind.db.Reader.<init>(Reader.java:133)
        at com.maxmind.db.Reader.<init>(Reader.java:117)
        at com.maxmind.geoip2.DatabaseReader.<init>(DatabaseReader.java:91)
        at com.maxmind.geoip2.DatabaseReader.<init>(DatabaseReader.java:62)
        at com.maxmind.geoip2.DatabaseReader$Builder.build(DatabaseReader.java:216)
        at com.ok.mmdbtest.MmdbUtil.getDataBaseReader(MmdbUtil.java:27)
        at com.ok.mmdbtest.MainActivity$onCreate$1.onClick(MainActivity.kt:24)
        at android.view.View.performClick(View.java:5265)
        at com.google.android.material.button.MaterialButton.performClick(MaterialButton.java:1119)
        at android.view.View$PerformClick.run(View.java:21534)
        at android.os.Handler.handleCallback(Handler.java:815)
        at android.os.Handler.dispatchMessage(Handler.java:104)
        at android.os.Looper.loop(Looper.java:207)
        at android.app.ActivityThread.main(ActivityThread.java:5788)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)
        at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107)

**Comment by sa2241182** [comment]
version: 'com.maxmind.geoip2:geoip2:2.16.1'

**Comment by sa2241182** [comment]
Normal use com.maxmind.geoip2:geoip2:2.11.0

**Comment by horgh** [comment]
Unfortunately, newer versions of this library require language features not available in Android 6, so you will need to stick with older versions. I think the latest you could use is 2.12.0. See also https://github.com/maxmind/MaxMind-DB-Reader-java/pull/96 where we discussed this a little regarding Android 7.

**Comment by sa2241182** [comment]
Thanks
