### ISSUE TITLE
Error when call GeoIP2-java

### ISSUE THREAD

**Issue by dongmo** [maxmind/GeoIP2-java#76]
I put dependency GeoIP2-java in maven project, but i have this error:

2016-10-08 17:20:26,482 ERROR [dispatcherServlet]: Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Handler processing failed; nested exception is java.lang.NoSuchMethodError: com.fasterxml.jackson.databind.node.ArrayNode.<init>(Lcom/fasterxml/jackson/databind/node/JsonNodeFactory;Ljava/util/List;)V] with root cause
java.lang.NoSuchMethodError: com.fasterxml.jackson.databind.node.ArrayNode.<init>(Lcom/fasterxml/jackson/databind/node/JsonNodeFactory;Ljava/util/List;)V
	at com.maxmind.db.Decoder.decodeArray(Decoder.java:272) ~[maxmind-db-1.2.1.jar:na]
	at com.maxmind.db.Decoder.decodeByType(Decoder.java:156) ~[maxmind-db-1.2.1.jar:na]
	at com.maxmind.db.Decoder.decode(Decoder.java:147) ~[maxmind-db-1.2.1.jar:na]
	at com.maxmind.db.Decoder.decodeMap(Decoder.java:281) ~[maxmind-db-1.2.1.jar:na]
	at com.maxmind.db.Decoder.decodeByType(Decoder.java:154) ~[maxmind-db-1.2.1.jar:na]
	at com.maxmind.db.Decoder.decode(Decoder.java:147) ~[maxmind-db-1.2.1.jar:na]
	at com.maxmind.db.Decoder.decode(Decoder.java:87) ~[maxmind-db-1.2.1.jar:na]
	at com.maxmind.db.Reader.<init>(Reader.java:132) ~[maxmind-db-1.2.1.jar:na]
	at com.maxmind.db.Reader.<init>(Reader.java:116) ~[maxmind-db-1.2.1.jar:na]
	at com.maxmind.geoip2.DatabaseReader.<init>(DatabaseReader.java:35) ~[geoip2-2.8.0.jar:2.8.0]
	at com.maxmind.geoip2.DatabaseReader.<init>(DatabaseReader.java:23) ~[geoip2-2.8.0.jar:2.8.0]
	at com.maxmind.geoip2.DatabaseReader$Builder.build(DatabaseReader.java:129) ~[geoip2-2.8.0.jar:2.8.0]

please help

**Comment by oschwald** [comment]
Please ensure that you are using `jackson-databind` `2.8.2`.

**Comment by oschwald** [comment]
I am closing this, but if you are experiencing the error when using the correct `jackson-databind` version, I'd be happy to reopen it.
