### ISSUE TITLE
org.apache.http.client not found.

### ISSUE THREAD

**Issue by Prasadph1993** [maxmind/GeoIP2-java#89]
Below is the Stack trace. App crashes because of above no package found exception.

java.lang.NoClassDefFoundError: Failed resolution of: Lorg/apache/http/client/config/RequestConfig;
                                                                                    at com.maxmind.geoip2.WebServiceClient.<init>(WebServiceClient.java:114)
                                                                                    at com.maxmind.geoip2.WebServiceClient.<init>(WebServiceClient.java:89)
                                                                                    at com.maxmind.geoip2.WebServiceClient$Builder.build(WebServiceClient.java:246)
                                                                                    at android.demo.timevisualization.MainActivity.onCreate(MainActivity.java:24)
                                                                                    at android.app.Activity.performCreate(Activity.java:5966)
                                                                                    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
                                                                                    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2408)
                                                                                    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2517)
                                                                                    at android.app.ActivityThread.access$800(ActivityThread.java:162)
                                                                                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1412)
                                                                                    at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                    at android.os.Looper.loop(Looper.java:189)
                                                                                    at android.app.ActivityThread.main(ActivityThread.java:5530)
                                                                                    at java.lang.reflect.Method.invoke(Native Method)
                                                                                    at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:950)
                                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:745)
                                                                                 Caused by: java.lang.ClassNotFoundException: Didn't find class "org.apache.http.client.config.RequestConfig" on path: DexPathList[[zip file "/data/app/android.demo.timevisualization-1/base.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
                                                                                    at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                                                    at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
                                                                                    at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
                                                                                    at com.maxmind.geoip2.WebServiceClient.<init>(WebServiceClient.java:114) 
                                                                                    at com.maxmind.geoip2.WebServiceClient.<init>(WebServiceClient.java:89) 
                                                                                    at com.maxmind.geoip2.WebServiceClient$Builder.build(WebServiceClient.java:246) 
                                                                                    at android.demo.timevisualization.MainActivity.onCreate(MainActivity.java:24) 
                                                                                    at android.app.Activity.performCreate(Activity.java:5966) 
                                                                                    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106) 
                                                                                    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2408) 
                                                                                    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2517) 
                                                                                    at android.app.ActivityThread.access$800(ActivityThread.java:162) 
                                                                                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1412) 
                                                                                    at android.os.Handler.dispatchMessage(Handler.java:106) 
                                                                                    at android.os.Looper.loop(Looper.java:189) 
                                                                                    at android.app.ActivityThread.main(ActivityThread.java:5530) 
                                                                                    at java.lang.reflect.Method.invoke(Native Method) 
                                                                                    at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:950) 
                                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:745) 
                                                                                	Suppressed: java.lang.ClassNotFoundException: org.apache.http.client.config.RequestConfig
                                                                                    at java.lang.Class.classForName(Native Method)
                                                                                    at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
                                                                                    at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
                                                                                    at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
                                                                                    		... 18 more
                                                                                 Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available

**Comment by oschwald** [comment]
This library requires Apache HttpClient as well as several other dependencies. Please make sure you have the JAR files for these loaded. If you aren't using Maven, you can download the with-dependencies zip file from our [releases page](https://github.com/maxmind/GeoIP2-java/releases).

**Comment by jigarfumakiya** [comment]
i do have include all library and dependencies
Still i got the error
check this out!!  

E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #1
                                                   Process: com.creativeera.google.mutalfunds, PID: 13154
                                                   java.lang.RuntimeException: An error occurred while executing doInBackground()
                                                       at android.os.AsyncTask$3.done(AsyncTask.java:325)
                                                       at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
                                                       at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
                                                       at java.util.concurrent.FutureTask.run(FutureTask.java:242)
                                                       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
                                                       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                       at java.lang.Thread.run(Thread.java:761)
                                                    Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lorg/apache/http/client/config/RequestConfig;
                                                       at com.mashape.unirest.http.options.Options.refresh(Options.java:70)
                                                       at com.mashape.unirest.http.options.Options.<clinit>(Options.java:46)
                                                       at com.mashape.unirest.http.options.Options.getOption(Options.java:42)
                                                       at com.mashape.unirest.http.HttpClientHelper.prepareRequest(HttpClientHelper.java:151)
                                                       at com.mashape.unirest.http.HttpClientHelper.request(HttpClientHelper.java:131)
                                                       at com.mashape.unirest.request.BaseRequest.asJson(BaseRequest.java:68)
                                                       at com.creativeera.google.mutalfunds.MainActivity$getapi.doInBackground(MainActivity.java:56)
                                                       at com.creativeera.google.mutalfunds.MainActivity$getapi.doInBackground(MainActivity.java:31)
                                                       at android.os.AsyncTask$2.call(AsyncTask.java:305)
                                                       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243) 
                                                       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
                                                       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
                                                       at java.lang.Thread.run(Thread.java:761) 
                                                    Caused by: java.lang.ClassNotFoundException: Didn't find class "org.apache.http.client.config.RequestConfig" on path: DexPathList[[zip file "/data/app/com.creativeera.google.mutalfunds-2/base.apk", zip file "/data/app/com.creativeera.google.mutalfunds-2/split_lib_dependencies_apk.apk", zip file "/data/app/com.creativeera.google.mutalfunds-2/split_lib_slice_0_apk.apk", zip file "/data/app/com.creativeera.google.mutalfunds-2/split_lib_slice_1_apk.apk", zip file "/data/app/com.creativeera.google.mutalfunds-2/split_lib_slice_2_apk.apk", zip file "/data/app/com.creativeera.google.mutalfunds-2/split_lib_slice_3_apk.apk", zip file "/data/app/com.creativeera.google.mutalfunds-2/split_lib_slice_4_apk.apk", zip file "/data/app/com.creativeera.google.mutalfunds-2/split_lib_slice_5_apk.apk", zip file "/data/app/com.creativeera.google.mutalfunds-2/split_lib_slice_6_apk.apk", zip file "/data/app/com.creativeera.google.mutalfunds-2/split_lib_slice_7_apk.apk", zip file "/data/app/com.creativeera.google.mutalfunds-2/split_lib_slice_8_apk.apk", zip file "/data/app/com.creativeera.google.mutalfunds-2/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/com.creativeera.google.mutalfunds-2/lib/arm, /system/lib, /vendor/lib]]
                                                       at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                       at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
                                                       at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                                                       at com.mashape.unirest.http.options.Options.refresh(Options.java:70) 
                                                       at com.mashape.unirest.http.options.Options.<clinit>(Options.java:46) 
                                                       at com.mashape.unirest.http.options.Options.getOption(Options.java:42) 
                                                       at com.mashape.unirest.http.HttpClientHelper.prepareRequest(HttpClientHelper.java:151) 
                                                       at com.mashape.unirest.http.HttpClientHelper.request(HttpClientHelper.java:131) 
                                                       at com.mashape.unirest.request.BaseRequest.asJson(BaseRequest.java:68) 
                                                       at com.creativeera.google.mutalfunds.MainActivity$getapi.doInBackground(MainActivity.java:56) 
                                                       at com.creativeera.google.mutalfunds.MainActivity$getapi.doInBackground(MainActivity.java:31) 
                                                       at android.os.AsyncTask$2.call(AsyncTask.java:305) 
                                                       at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
                                                       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243) 
                                                       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
                                                       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
                                                       at java.lang.Thread.run(Thread.java:761) 


AND that is my Gradle file


dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation 'com.android.support:appcompat-v7:26.1.0'
    implementation 'com.android.support.constraint:constraint-layout:1.1.0'
    testImplementation 'junit:junit:4.12'
    androidTestCompile 'com.android.support:support-annotations:26.1.0'
    //    compile 'org.apache.httpcomponents:httpclient-android:4.3.3'
    // gradle depedencies
    compile 'com.rapidapi:rapidconnect-android:0.1'
    androidTestImplementation 'com.android.support.test:runner:1.0.2'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'
    implementation files('libs/httpcore-nio-4.1-beta2.jar')
    implementation files('libs/unirest-java-1.4.9.jar')
    implementation files('libs/json-20180130.jar')
    implementation files('libs/org.apache.httpcomponents.httpclient-4.1.0.jar')
    implementation files('libs/httpclient-4.1.1.jar')
}

Thanks!!

**Comment by oschwald** [comment]
@jigarfumakiya, you appear to be pulling in httpclient 4.1.0. This library is compiled against 4.5.5.
